### ISSUE TITLE
[LtF - Pt 2] Fix last test case

### ISSUE THREAD

**Issue by Mirclus** [Patryk27/website#1]
Hi,

The last testcase show in this article won't succeed, you will get 2 failed asserts:
- The first propagate will assert, as the input (1 value) does not match the weights (2)
- The second assert fails, because `propagate` cannot return negative values (so the result is 0).

Additionally, as you are already using a struct for the topology, you could also use [`std::num::NonZeroUsize`](https://doc.rust-lang.org/std/num/struct.NonZeroUsize.html).

Otherwise, good post, keep up the good work.

**Comment by Patryk27** [comment]
Hi,

You've got quite an eye - I fixed the code example :-)
As for the `NonZeroUsize` - it's a great tip, I'll try introducing it in the third part.

Thanks!
