### ISSUE TITLE
Trigonometry in Learning to Fly Part 4

### ISSUE THREAD

**Issue by FreePlacki** [Patryk27/website#11]
When you explain the process of drawing the triangles, you convert the angle to radians:

```
2 * PI = 360°
     x = 60°

360° * x = 2 * PI * 60°    | divide by 2
180° * x = PI * 60°        | divide by 180°
       x = PI * 60° / 180° | simplify
       x = PI * 2 / 3      | shuffle constant to left
       x = 2 / 3 * PI      | enjoy
```
But `x = 60° = 1 / 3 * PI`.
The values you obtained: `2/3 PI` and `4/3 PI` are correct, but that's not because we rotate by `60°` and `120°` but instead by `120°` and `240°`.

---
Also one small mistake: on the drawing of the unit circle, labels on the axis are swapped (if you say that `x=cos(α)` and `y=sin(α)`).

**Comment by Patryk27** [comment]
Hi, thanks for reporting! I'll take a look over the weekend and update the article 🙂
