### ISSUE TITLE
Grammatical Errors: learning-to-fly-pt-1

### ISSUE THREAD

**Issue by vijaynyaya** [Patryk27/website#12]
[As a fellow human, ***you ~~are~~ might be aware*** that brains are made of neurons connected via synapses](https://github.com/Patryk27/website/blob/b98def44183937c1fb2ec95b3055ed60d257e5e9/src/content/posts/learning-to-fly-pt1/body.html#L211)

**Comment by Patryk27** [comment]
Whoopsie, thanks!
