### ISSUE TITLE
Number of weights in neuron should be number of inputs

### ISSUE THREAD

**Issue by andrewliu08** [Patryk27/website#13]
https://github.com/Patryk27/shorelark/blob/60bb90b5f233200c2b9d16dc1432471f57f236c1/libs/neural-network/src/neuron.rs#L16
```
impl Neuron {
    ...
    pub fn random(rng: &mut dyn RngCore, output_neurons: usize) -> Self {
}
```

`input_neurons` should be the parameter name rather than `output_neurons`, since the number of neuron weights depends on number of inputs

**Comment by Patryk27** [comment]
Great catch! Thanks, fixed; I'm going to fix the articles in a moment as well 🙂
