### ISSUE TITLE
x/y swapped in test compared to drawing

### ISSUE THREAD

**Issue by marcustrp** [Patryk27/website#15]
On https://pwy.io/posts/learning-to-fly-pt4/ , for the test different_fov_angles, the x/y for foods is swapped when compared to the ASCII-drawings for the test .

In the ASCII-drawing, food is at top and bottom, but in the test, food is actually placed left and right:

foods: vec![
    food(0.0, 0.0),
    food(0.0, 0.33),
    food(0.0, 0.66),
    food(0.0, 1.0),
    food(1.0, 0.0),
    food(1.0, 0.33),
    food(1.0, 0.66),
    food(1.0, 1.0),
],

It should be:

foods: vec![
    food(0.0, 0.0),
    food(0.33, 0.0),
    food(0.66, 0.0),
    food(1.0, 0.0),
    food(0.0, 1.0),
    food(0.33, 1.0),
    food(0.66, 1.0),
    food(1.0, 1.0),
],

Anyway, huge thanks for the 4-part article series! I started learning Rust a week ago, wanted to test wasm and have for a few years wanted to try out a neural network from scratch. Perfect combo with the amazing quality of your articles (progression, explanations, humor...)

**Comment by Patryk27** [comment]
Thanks for reporting, fixed! -- I'm glad you've liked it 🙂
