### ISSUE TITLE
Pointer size in Learning to Fly, Part 4

### ISSUE THREAD

**Issue by teor2345** [Patryk27/website#9]
Hi Patryk,

In Learning to Fly, Part 4, you say:
> it’s -16, because r0 & r1 are 64-bit numbers, so: 2 * 64 / 8 bits per byte = 16 bytes.

But I'm wondering if there are actually 4 * 32 bit numbers instead?

The wasm code has some functions that end in 32, and some divisions by 4, which typically indicate 32 bit integers and pointers.

There are definitely two variables on the stack. But there could also be 2 more hidden variables: the pointer and length for the returned string. (I'm not sure, because I don't know the wasm function calling conventions. If the caller creates stack space for the return values, then I'm not sure what those extra 8 bytes are.)

**Comment by Patryk27** [comment]
Hi,

Yes, I think you're right - `getInt32Memory0()` suggests 32-bit-wide pointers, plain as day 🙂 

My guess for those 8 extra bytes would be the calling convention, but I've been unable to confirm this information - for now I'll just get rid of this paragraph from the message, to avoid confusing the readers.

Thanks for reporting!
